# Generated by Django 3.0.2 on 2020-05-08 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zymlover.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=20)),
                ('emails', models.EmailField(default=0, max_length=100, null=True)),
                ('phones', models.IntegerField()),
                ('addresses', models.CharField(max_length=300)),
                ('fnames', models.CharField(max_length=20)),
                ('mnames', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('statuses', models.CharField(choices=[('d', 'Draft'), ('p', 'Publishes'), ('w', 'Withdrawn')], default='d', max_length=1)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=20, validators=[zymlover.models.Contact.min_length_check])),
                ('Images', models.FileField(null=True, upload_to='zymlover/')),
                ('b', models.EmailField(default=0, max_length=100, null=True)),
                ('c', models.CharField(max_length=500)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
