# Generated by Django 3.0.2 on 2020-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zymlover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parentcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zymlover.Comments'),
        ),
    ]
